"""
Problem 12
==========


   The sequence of triangle numbers is generated by adding the natural
   numbers. So the 7^th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 =
   28. The first ten terms would be:

                    1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

   Let us list the factors of the first seven triangle numbers:

      1: 1
      3: 1,3
      6: 1,2,3,6
     10: 1,2,5,10
     15: 1,3,5,15
     21: 1,3,7,21
     28: 1,2,4,7,14,28

   We can see that 28 is the first triangle number to have over five
   divisors.

   What is the value of the first triangle number to have over five hundred
   divisors?


   Answer: 8091de7d285989bbfa9a2f9f3bdcc7c0
"""
import timing
import math

for x in get_triangle_numbers():
    divisors = 0
    for div in range(2, round(math.sqrt(x)+1)):
        if x % div == 0:
            divisors += 2
    if divisors > 500:
        break
    

print(x)

